#ifndef CMD_LIST_SERVEUR_H
#define CMD_LIST_SERVEUR_H

#define CONNECTION "CONN"
#define CONNECTION_SUCCESS "CSUC"
#define CONNECTION_FAILLED "CBAD"
#define EXIT_CLIENT "EXIT"
#define PUBLIC_MSG "PUBL"
#define PRIVATE "PRIV"
#define PRIVATE_OK "PROK"
#define PRIVATE_ERR "PERR"
#define LIST "LIST"
#define NB_USER "NBUS"
#define SHUTDOWN "SHUT"

#endif //CMD_LIST_H